### PR TITLE
Tighten up the Jenkinsfile for ci.j.io

### PR DESCRIPTION
**Pull request by rtyler**
At some point I would like to replace this with the [global library work](https://github.com/jenkins-infra/pipeline-global-library) I have been tinkering with in the lab.

### CODE REVIEW

**Comment by rtyler** [comment]
Turns out this isn't going to work until jenkinsci/docker-workflow-plugin#63 is released :frowning:

**Comment by i386** [comment]
@rtyler this is failing right now. I will merge when that build passes.

**Comment by rtyler** [comment]
@i386 blammo

**Comment by i386** [comment]
🐝🐝🐝

**Pull request merged**
