### PR TITLE
[FIXED JENKINS-45478] Added an API that can be used to provide the UTM details

### PR DESCRIPTION
**Pull request by stephenc**
Review comments on https://github.com/jenkinsci/display-url-api-plugin/pull/15 indicated that the plugin maintainer desired to allow more generic decoration outside of the UTM parameters.

This pull request supersedes #15 and provides an API that will allow other plugins to decorate the URLs with query parameters as necessary.

### CODE REVIEW

**Comment by stephenc** [comment]
@michaelneale @i386 WDYT?

**Comment by stephenc** [comment]
Unclear what is up with the PR builder... likely the parent pomis too old for the current jenkinsfile

**Comment by michaelneale** [comment]
@stephenc looks reasonable to me - not sure if I can review it more closely than that. Maybe @vivek or @olamy can cast eyes over it. Is there any need to manual testing to this or a non controversial change. 

Yeah probably needs to bump dependencies as ooooolld!

**Comment by michaelneale** [comment]
@stephenc do you have perms to release this? conceptually seems good to me (would be nice if build would run...)

**Comment by stephenc** [comment]
I don’t have permission. Builds perfectly fine “on my machine”. Hoping you could prod @i386 and persuade him to release it as a favour ;-)

**Comment by stephenc** [comment]
The additional test coverage in this PR should suffice IMO

**Comment by michaelneale** [comment]
@stephenc no need to find a new owner if we want to release it.

**Comment by michaelneale** [comment]
hey @imeredith could you merge/release this at some point?

**Comment by michaelneale** [comment]
I ran tests locally and all good 👍 from me for this change.

**Comment by imeredith** [comment]
@michaelneale ugh i can try, its been so long i cant remember if there is anything special to do

**Pull request merged**
