### PR TITLE
[JENKINS-71715] Handle console urls

### PR DESCRIPTION
**Pull request by jgreffe**
https://issues.jenkins.io/browse/JENKINS-71715
Draft demonstrating the new console URL handling.

The idea is to provide a new method `getConsoleURL(Run<?, ?> run)`, which allows any provider to redirection to a specific console link.

All `/job/<name>/<build number>/display/redirect?page=console` will redirect to this method.

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by dwnusbaum** [comment]
I am looking to see what downstream consumers would use this endpoint. It might actually be unnecessary with the changes to the APIs in https://github.com/jenkinsci/jenkins/pull/8321.

**Comment by jgreffe** [comment]
Not useful anymore, as https://github.com/jenkinsci/jenkins/pull/8321/files/ae52b83c05129c418eb9fea12346a33303f887e0#diff-86a37a673934cb2164356b37c70893e0904526d22ef750742d730b48c29fe4e1 is preferred.

**Comment by dwnusbaum** [comment]
Just for the record, [`email-ext` templates](https://github.com/search?q=repo%3Ajenkinsci%2Femail-ext-plugin%20console&type=code) are a case where being able to product display URLs directly to the console could be useful.

**Comment by jglick** [comment]
The proposed `display/redirect?page=console` URL pattern would be useful in cases where you can predict the `Run.url` but do not have a `Run` object on hand to pass to `ConsoleUrlProvider`, for example because the code to create the link is not running inside Jenkins.

**Comment by dwnusbaum** [comment]
When we originally closed this, it was because all of the use cases at the time were for producing relative links to the console from within Jenkins, mostly from Jelly templates, and so `DisplayURLProvider` was not a good match, hence `ConsoleUrlProvider`. If you now have a use case for a `DisplayURLProvider.getConsoleURL` method, I don't think there is any problem with this PR, and it could be reopened/recreated.

**Comment by jglick** [comment]
Though just `display/redirect` seems to work? Or only under certain conditions?

**Comment by dwnusbaum** [comment]
For some providers (e.g., CPE, Pipeline Graph View, Blue Ocean), the main run page basically is the console page (I recall now that this was also partly why we decided not to pursue this at the time), so configuring that provider is already good enough. Adding a new API method would mainly help for the classic console page. If we also added a way to link to logs for a particular step, then a new API method would be more relevant for all of the providers.

**Pull request closed without merging**
