### PR TITLE
JENKINS-39580 Allow the user to configure a preferred provider 

### PR DESCRIPTION
**Pull request by i386**
[JENKINS-39580](https://issues.jenkins-ci.org/browse/JENKINS-39580)

Allows the user to set their preferred UI in the users settings

Depends on https://github.com/jenkinsci/display-url-api-plugin/pull/4

user admin istrator configuration jenkins 2016-12-04 13-41-22

### CODE REVIEW

**Comment by daniel-beck** [comment]
This appears to be unrelated to JENKINS-39580. All that was asking for is a global option so admins have a choice to opt in to / out of BO display URLs globally.

Additionally the redirect handling looks very limited: It does not appear to be flexible enough to support URLs besides the most basic job / run / test (this one is necessarily complicated). Not sure whether that's an issue.

There is no i18n support.

**Comment by michaelneale** [comment]
failure seems environmental: 

```
[ERROR] Could not create local repository at /var/maven/.m2/repository -> [Help 1]
```

**Comment by i386** [comment]
@daniel-beck help file and i18n done.

**Comment by michaelneale** [comment]
LGTM

**Pull request merged**
