### PR TITLE
[FIXED JENKINS-45478] Add UTM query parameter support

### PR DESCRIPTION
**Pull request by stephenc**
See [JENKINS-45478](https://issues.jenkins-ci.org/browse/JENKINS-45478)

@reviewbybees

### CODE REVIEW

**Comment by i386** [comment]
@stephenc haven't forgot this but unlikely going to get to it this week.

**Comment by michaelneale** [comment]
I like it - also I learned what all those "utm" things mean

**Comment by KostyaSha** [comment]
Status?

**Comment by michaelneale** [comment]
Ping @i386?

**Comment by i386** [comment]
I think I would prefer to see a implementation where we had a builder that could be used for adding any additional parameters - not just UTMs.

**Comment by stephenc** [comment]
Closing in favour of #20

**Pull request closed without merging**
